// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVm2PKyu-nbDOO120enFVSf20nXFG0gI8',
    appId: '1:1002875847037:web:cc02bc1e685e39411d0c14',
    messagingSenderId: '1002875847037',
    projectId: 'rubrica-c3-dmovil',
    authDomain: 'rubrica-c3-dmovil.firebaseapp.com',
    storageBucket: 'rubrica-c3-dmovil.firebasestorage.app',
    measurementId: 'G-YE96DM9VDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAomf8ZkyaLLFw227-J4gYveHazZliEL98',
    appId: '1:1002875847037:android:08fa9b3fb4621f211d0c14',
    messagingSenderId: '1002875847037',
    projectId: 'rubrica-c3-dmovil',
    storageBucket: 'rubrica-c3-dmovil.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVm2PKyu-nbDOO120enFVSf20nXFG0gI8',
    appId: '1:1002875847037:web:fb064516a4c200341d0c14',
    messagingSenderId: '1002875847037',
    projectId: 'rubrica-c3-dmovil',
    authDomain: 'rubrica-c3-dmovil.firebaseapp.com',
    storageBucket: 'rubrica-c3-dmovil.firebasestorage.app',
    measurementId: 'G-5PLBWZ7DBT',
  );
}
